package pl.polsl.javasourcecodescomparator.view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class MainView {
    private JPanel mainPanel;
    private JFileChooser fileChooser;
    private JTextField similarityPercentageTextField;
    private JLabel similarityPercentageLabel;
    private JCheckBox sameAuthorCheckBox;
    private JCheckBox sameProjectCheckBox;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JTextField getSimilarityPercentageTextField() {
        return similarityPercentageTextField;
    }

    public JCheckBox getSameAuthorCheckBox() {
        return sameAuthorCheckBox;
    }

    public JCheckBox getSameProjectCheckBox() {
        return sameProjectCheckBox;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(14, 4, new Insets(0, 0, 0, 0), -1, -1));
        fileChooser = new JFileChooser();
        mainPanel.add(fileChooser, new GridConstraints(0, 0, 14, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(720, 720), null, 0, false));
        similarityPercentageLabel = new JLabel();
        similarityPercentageLabel.setHorizontalAlignment(0);
        similarityPercentageLabel.setHorizontalTextPosition(0);
        similarityPercentageLabel.setText("Minimalna % zgodność plików");
        mainPanel.add(similarityPercentageLabel, new GridConstraints(2, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        similarityPercentageTextField = new JTextField();
        mainPanel.add(similarityPercentageTextField, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(4, 2, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(0, 3, 14, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        sameAuthorCheckBox = new JCheckBox();
        sameAuthorCheckBox.setSelected(false);
        sameAuthorCheckBox.setText("Porównywanie plików tego samego autora");
        mainPanel.add(sameAuthorCheckBox, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        sameProjectCheckBox = new JCheckBox();
        sameProjectCheckBox.setText("Porównywanie plików wewnątrz projektu");
        mainPanel.add(sameProjectCheckBox, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
